/* automatically generated by rust-bindgen 0.60.1 */

use sgx_types::*;

extern "C" {
    pub fn append_data(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        pool_one: *const u8,
        len: size_t,
        pool_two: *const u8,
        len_two: size_t,
    ) -> sgx_status_t;
}
